/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd2;

import com.mongodb.BasicDBObject;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoDatabase;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author Daniel RC
 */
public class ProyectoBD2 extends javax.swing.JFrame {

    PersonaConexion personaconexion = new PersonaConexion();
    Persona persona;
    Farmacia farmacia;
    Laboratorio laboratorio;
    Producto producto;
    ArrayList<Producto> productos = new ArrayList();
    ArrayList<Persona> farmaceuticos = new ArrayList();
    ArrayList<Persona> propietarios = new ArrayList();
    Document consulta;
    MongoClient mongoClient = MongoClients.create(
            "mongodb+srv://JoseDanielRC:Daniel08@cluster0.nvrwy.mongodb.net/test?retryWrites=true&w=majority");
    MongoDatabase database = mongoClient.getDatabase("test");

    /**
     * Creates new form ProyectoBD2
     */
    public ProyectoBD2() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crear = new javax.swing.JDialog();
        jb_crearpersona = new javax.swing.JButton();
        jb_crearfarmacia = new javax.swing.JButton();
        jb_crearlab = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jd_crearpersona = new javax.swing.JDialog();
        jtxt_idpersona = new javax.swing.JTextField();
        jtxt_nombrepersona = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jb_registrarpersona = new javax.swing.JButton();
        jd_crearfarmacia = new javax.swing.JDialog();
        jtxt_idfarmacia = new javax.swing.JTextField();
        jtxt_nombrefarmacia = new javax.swing.JTextField();
        jtxt_direccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jb_registrarfarmacia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_productosxfarmacia = new javax.swing.JTable();
        jb_agregarproductoxfarmacia = new javax.swing.JButton();
        jb_agregarproductoxfarmacia1 = new javax.swing.JButton();
        jb_agregarproductoxfarmacia2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_personasxfarmacia = new javax.swing.JTable();
        jd_crearlaboratorio = new javax.swing.JDialog();
        jtxt_nombrelaboratorio = new javax.swing.JTextField();
        jtxt_idlaboratorio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jb_registrarlaboratorio = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_productosxlaboratorio = new javax.swing.JTable();
        jb_agregarproductoxfarmacia3 = new javax.swing.JButton();
        jd_crearproducto = new javax.swing.JDialog();
        jtxt_idproducto = new javax.swing.JTextField();
        jtxt_nombreproducto = new javax.swing.JTextField();
        jtxt_tipoproducto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jb_registrarfarmacia1 = new javax.swing.JButton();
        jd_ModificarPersonas = new javax.swing.JDialog();
        jcb_idPersona = new javax.swing.JComboBox<>();
        jtxt_modificarnombrePersona = new javax.swing.JTextField();
        jb_modificarpersona = new javax.swing.JButton();
        jd_Modificar = new javax.swing.JDialog();
        jb_crearpersona1 = new javax.swing.JButton();
        jb_crearlab1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jb_crearfarmacia1 = new javax.swing.JButton();
        jd_ModificarFarmacias = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxt_modificarnombrefarmacia = new javax.swing.JTextField();
        jtxt_modificardireccionfarmacia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jb_modificarfarmacia = new javax.swing.JButton();
        jcb_idfarmacia = new javax.swing.JComboBox<>();
        jd_modificarproducto = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_productos = new javax.swing.JTable();
        jb_modificarproducto = new javax.swing.JButton();
        jd_modificarproductoventana = new javax.swing.JDialog();
        tf_modificaridproducto = new javax.swing.JTextField();
        tf_modificarnombreproducto = new javax.swing.JTextField();
        tf_modificartipoproducto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jb_modfinalproducto = new javax.swing.JButton();
        jd_modificarLab = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jtxtmodifcarnombrelaboratorio = new javax.swing.JTextField();
        jcb_modificarlaboratorio = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jd_eliminar = new javax.swing.JDialog();
        jb_eliminarpersona = new javax.swing.JButton();
        jb_eliminarlaboratorio = new javax.swing.JButton();
        jb_eliminarproducto = new javax.swing.JButton();
        jb_eliminarfarmacia = new javax.swing.JButton();
        jd_EliminarFarmacia = new javax.swing.JDialog();
        jScrollPane10 = new javax.swing.JScrollPane();
        jt_eliminarfarmacia = new javax.swing.JTable();
        jbt_eliminarfarmacias = new javax.swing.JButton();
        jd_EliminarProducto = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jt_eliminarproductos = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jd_EliminarLaboratorio = new javax.swing.JDialog();
        jScrollPane8 = new javax.swing.JScrollPane();
        jt_eliminarlaboratorios = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jd_EliminarPersonas = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        jt_eliminarpersonas = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jb_crear = new javax.swing.JButton();
        jb_modificar = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();

        jb_crearpersona.setText("Persona");
        jb_crearpersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearpersonaActionPerformed(evt);
            }
        });

        jb_crearfarmacia.setText("Farmacia");
        jb_crearfarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearfarmaciaActionPerformed(evt);
            }
        });

        jb_crearlab.setText("Laboratorio");
        jb_crearlab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearlabActionPerformed(evt);
            }
        });

        jButton1.setText("Producto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_crearLayout = new javax.swing.GroupLayout(jd_crear.getContentPane());
        jd_crear.getContentPane().setLayout(jd_crearLayout);
        jd_crearLayout.setHorizontalGroup(
            jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_crearlab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_crearfarmacia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_crearpersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jd_crearLayout.setVerticalGroup(
            jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jb_crearfarmacia)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(38, 38, 38)
                .addComponent(jb_crearlab)
                .addGap(35, 35, 35)
                .addComponent(jb_crearpersona)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jtxt_idpersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_idpersonaActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Nombre");

        jb_registrarpersona.setText("Registrar");
        jb_registrarpersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_registrarpersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_crearpersonaLayout = new javax.swing.GroupLayout(jd_crearpersona.getContentPane());
        jd_crearpersona.getContentPane().setLayout(jd_crearpersonaLayout);
        jd_crearpersonaLayout.setHorizontalGroup(
            jd_crearpersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearpersonaLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jd_crearpersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_registrarpersona)
                    .addGroup(jd_crearpersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jd_crearpersonaLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxt_nombrepersona, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jd_crearpersonaLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(38, 38, 38)
                            .addComponent(jtxt_idpersona, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48))
        );
        jd_crearpersonaLayout.setVerticalGroup(
            jd_crearpersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearpersonaLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jd_crearpersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_idpersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(59, 59, 59)
                .addGroup(jd_crearpersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_nombrepersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jb_registrarpersona)
                .addGap(24, 24, 24))
        );

        jtxt_idfarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_idfarmaciaActionPerformed(evt);
            }
        });

        jtxt_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_direccionActionPerformed(evt);
            }
        });

        jLabel3.setText("IdFarmacia");

        jLabel4.setText("Nombre");

        jLabel5.setText("Direcciòn");

        jb_registrarfarmacia.setText("Registar");
        jb_registrarfarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_registrarfarmaciaActionPerformed(evt);
            }
        });

        jt_productosxfarmacia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "_id", "IdProducto", "NombreProducto", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(jt_productosxfarmacia);

        jb_agregarproductoxfarmacia.setText("Agregar");
        jb_agregarproductoxfarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarproductoxfarmaciaActionPerformed(evt);
            }
        });

        jb_agregarproductoxfarmacia1.setText("Agregar como Farmaceutico");
        jb_agregarproductoxfarmacia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarproductoxfarmacia1ActionPerformed(evt);
            }
        });

        jb_agregarproductoxfarmacia2.setText("Agregar como Propietario");
        jb_agregarproductoxfarmacia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarproductoxfarmacia2ActionPerformed(evt);
            }
        });

        jt_personasxfarmacia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "_id", "IdP", "NombreP"
            }
        ));
        jScrollPane4.setViewportView(jt_personasxfarmacia);

        javax.swing.GroupLayout jd_crearfarmaciaLayout = new javax.swing.GroupLayout(jd_crearfarmacia.getContentPane());
        jd_crearfarmacia.getContentPane().setLayout(jd_crearfarmaciaLayout);
        jd_crearfarmaciaLayout.setHorizontalGroup(
            jd_crearfarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearfarmaciaLayout.createSequentialGroup()
                .addGroup(jd_crearfarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearfarmaciaLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jd_crearfarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearfarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_crearfarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crearfarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtxt_direccion)
                                .addComponent(jtxt_idfarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtxt_nombrefarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearfarmaciaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_registrarfarmacia)
                        .addGap(65, 65, 65)))
                .addGroup(jd_crearfarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_crearfarmaciaLayout.createSequentialGroup()
                        .addGap(0, 43, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_crearfarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jb_agregarproductoxfarmacia2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_agregarproductoxfarmacia1))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_crearfarmaciaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_agregarproductoxfarmacia)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jd_crearfarmaciaLayout.setVerticalGroup(
            jd_crearfarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearfarmaciaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jb_agregarproductoxfarmacia)
                .addGap(148, 148, 148)
                .addComponent(jb_agregarproductoxfarmacia1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_agregarproductoxfarmacia2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_crearfarmaciaLayout.createSequentialGroup()
                .addGroup(jd_crearfarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearfarmaciaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_crearfarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crearfarmaciaLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jd_crearfarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jtxt_nombrefarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_crearfarmaciaLayout.createSequentialGroup()
                                .addGroup(jd_crearfarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxt_idfarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(89, 89, 89)
                                .addComponent(jLabel5))))
                    .addGroup(jd_crearfarmaciaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jd_crearfarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearfarmaciaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jb_registrarfarmacia))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearfarmaciaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))))
        );

        jtxt_idlaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_idlaboratorioActionPerformed(evt);
            }
        });

        jLabel6.setText("IdLaboratorio");

        jLabel7.setText("Nombre");

        jb_registrarlaboratorio.setText("Registar");
        jb_registrarlaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_registrarlaboratorioActionPerformed(evt);
            }
        });

        jt_productosxlaboratorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "_id", "IdProducto", "NombreProducto", "Tipo"
            }
        ));
        jScrollPane3.setViewportView(jt_productosxlaboratorio);

        jb_agregarproductoxfarmacia3.setText("Agregar");
        jb_agregarproductoxfarmacia3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarproductoxfarmacia3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_crearlaboratorioLayout = new javax.swing.GroupLayout(jd_crearlaboratorio.getContentPane());
        jd_crearlaboratorio.getContentPane().setLayout(jd_crearlaboratorioLayout);
        jd_crearlaboratorioLayout.setHorizontalGroup(
            jd_crearlaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearlaboratorioLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jd_crearlaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearlaboratorioLayout.createSequentialGroup()
                        .addGroup(jd_crearlaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(32, 32, 32)
                        .addGroup(jd_crearlaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtxt_nombrelaboratorio)
                            .addComponent(jtxt_idlaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_crearlaboratorioLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jb_registrarlaboratorio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jd_crearlaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearlaboratorioLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearlaboratorioLayout.createSequentialGroup()
                        .addComponent(jb_agregarproductoxfarmacia3)
                        .addGap(220, 220, 220))))
        );
        jd_crearlaboratorioLayout.setVerticalGroup(
            jd_crearlaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearlaboratorioLayout.createSequentialGroup()
                .addGroup(jd_crearlaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearlaboratorioLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jd_crearlaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(jd_crearlaboratorioLayout.createSequentialGroup()
                                .addGroup(jd_crearlaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxt_idlaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(33, 33, 33)
                                .addComponent(jtxt_nombrelaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_crearlaboratorioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jd_crearlaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearlaboratorioLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jb_registrarlaboratorio))
                    .addGroup(jd_crearlaboratorioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jb_agregarproductoxfarmacia3)))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jtxt_idproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_idproductoActionPerformed(evt);
            }
        });

        jtxt_tipoproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_tipoproductoActionPerformed(evt);
            }
        });

        jLabel8.setText("Tipo");

        jLabel9.setText("Nombre");

        jLabel10.setText("IdProducto");

        jb_registrarfarmacia1.setText("Registar");
        jb_registrarfarmacia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_registrarfarmacia1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_crearproductoLayout = new javax.swing.GroupLayout(jd_crearproducto.getContentPane());
        jd_crearproducto.getContentPane().setLayout(jd_crearproductoLayout);
        jd_crearproductoLayout.setHorizontalGroup(
            jd_crearproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
            .addGroup(jd_crearproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_crearproductoLayout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addGroup(jd_crearproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8))
                    .addGap(32, 32, 32)
                    .addGroup(jd_crearproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_crearproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtxt_tipoproducto)
                            .addComponent(jtxt_nombreproducto)
                            .addComponent(jtxt_idproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jb_registrarfarmacia1))
                    .addContainerGap(71, Short.MAX_VALUE)))
        );
        jd_crearproductoLayout.setVerticalGroup(
            jd_crearproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
            .addGroup(jd_crearproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_crearproductoLayout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addGroup(jd_crearproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jd_crearproductoLayout.createSequentialGroup()
                            .addGroup(jd_crearproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtxt_idproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addGap(33, 33, 33)
                            .addComponent(jtxt_nombreproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel9))
                    .addGap(34, 34, 34)
                    .addGroup(jd_crearproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtxt_tipoproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGap(30, 30, 30)
                    .addComponent(jb_registrarfarmacia1)
                    .addContainerGap(100, Short.MAX_VALUE)))
        );

        jcb_idPersona.setModel(new DefaultComboBoxModel());
        jcb_idPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_idPersonaActionPerformed(evt);
            }
        });

        jb_modificarpersona.setText("Modificar");
        jb_modificarpersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarpersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_ModificarPersonasLayout = new javax.swing.GroupLayout(jd_ModificarPersonas.getContentPane());
        jd_ModificarPersonas.getContentPane().setLayout(jd_ModificarPersonasLayout);
        jd_ModificarPersonasLayout.setHorizontalGroup(
            jd_ModificarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModificarPersonasLayout.createSequentialGroup()
                .addGroup(jd_ModificarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ModificarPersonasLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jd_ModificarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcb_idPersona, 0, 164, Short.MAX_VALUE)
                            .addComponent(jtxt_modificarnombrePersona)))
                    .addGroup(jd_ModificarPersonasLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jb_modificarpersona, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jd_ModificarPersonasLayout.setVerticalGroup(
            jd_ModificarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModificarPersonasLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jcb_idPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jtxt_modificarnombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(jb_modificarpersona)
                .addGap(108, 108, 108))
        );

        jb_crearpersona1.setText("Persona");
        jb_crearpersona1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearpersona1ActionPerformed(evt);
            }
        });

        jb_crearlab1.setText("Laboratorio");
        jb_crearlab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearlab1ActionPerformed(evt);
            }
        });

        jButton2.setText("Producto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jb_crearfarmacia1.setText("Farmacia");
        jb_crearfarmacia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearfarmacia1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_ModificarLayout = new javax.swing.GroupLayout(jd_Modificar.getContentPane());
        jd_Modificar.getContentPane().setLayout(jd_ModificarLayout);
        jd_ModificarLayout.setHorizontalGroup(
            jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModificarLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_crearlab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_crearfarmacia1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_crearpersona1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jd_ModificarLayout.setVerticalGroup(
            jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModificarLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jb_crearfarmacia1)
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addGap(38, 38, 38)
                .addComponent(jb_crearlab1)
                .addGap(35, 35, 35)
                .addComponent(jb_crearpersona1)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jLabel11.setText("IdFarmacia");

        jLabel12.setText("Nombre");

        jtxt_modificarnombrefarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_modificarnombrefarmaciaActionPerformed(evt);
            }
        });

        jLabel13.setText("Direcciòn");

        jb_modificarfarmacia.setText("Modificar");
        jb_modificarfarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarfarmaciaActionPerformed(evt);
            }
        });

        jcb_idfarmacia.setModel(new DefaultComboBoxModel());

        javax.swing.GroupLayout jd_ModificarFarmaciasLayout = new javax.swing.GroupLayout(jd_ModificarFarmacias.getContentPane());
        jd_ModificarFarmacias.getContentPane().setLayout(jd_ModificarFarmaciasLayout);
        jd_ModificarFarmaciasLayout.setHorizontalGroup(
            jd_ModificarFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModificarFarmaciasLayout.createSequentialGroup()
                .addGroup(jd_ModificarFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ModificarFarmaciasLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jb_modificarfarmacia))
                    .addGroup(jd_ModificarFarmaciasLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jd_ModificarFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_ModificarFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ModificarFarmaciasLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtxt_modificarnombrefarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ModificarFarmaciasLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtxt_modificardireccionfarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_ModificarFarmaciasLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jcb_idfarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jd_ModificarFarmaciasLayout.setVerticalGroup(
            jd_ModificarFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ModificarFarmaciasLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jd_ModificarFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jcb_idfarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jd_ModificarFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_modificarnombrefarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(28, 28, 28)
                .addGroup(jd_ModificarFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_modificardireccionfarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jb_modificarfarmacia)
                .addGap(71, 71, 71))
        );

        jt_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "_id", "IdProducto", "NombreProducto", "Tipo"
            }
        ));
        jScrollPane2.setViewportView(jt_productos);

        jb_modificarproducto.setText("Modificar");
        jb_modificarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarproductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_modificarproductoLayout = new javax.swing.GroupLayout(jd_modificarproducto.getContentPane());
        jd_modificarproducto.getContentPane().setLayout(jd_modificarproductoLayout);
        jd_modificarproductoLayout.setHorizontalGroup(
            jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarproductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(jb_modificarproducto)
                .addGap(111, 111, 111))
        );
        jd_modificarproductoLayout.setVerticalGroup(
            jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarproductoLayout.createSequentialGroup()
                .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificarproductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_modificarproductoLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jb_modificarproducto)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel14.setText("Id");

        jLabel15.setText("Nombre");

        jLabel16.setText("Tipo");

        jb_modfinalproducto.setText("Guardar");
        jb_modfinalproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modfinalproductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_modificarproductoventanaLayout = new javax.swing.GroupLayout(jd_modificarproductoventana.getContentPane());
        jd_modificarproductoventana.getContentPane().setLayout(jd_modificarproductoventanaLayout);
        jd_modificarproductoventanaLayout.setHorizontalGroup(
            jd_modificarproductoventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarproductoventanaLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jd_modificarproductoventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(28, 28, 28)
                .addGroup(jd_modificarproductoventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_modificaridproducto)
                    .addComponent(tf_modificarnombreproducto)
                    .addComponent(tf_modificartipoproducto, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificarproductoventanaLayout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(jb_modfinalproducto)
                .addGap(68, 68, 68))
        );
        jd_modificarproductoventanaLayout.setVerticalGroup(
            jd_modificarproductoventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarproductoventanaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jd_modificarproductoventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_modificarproductoventanaLayout.createSequentialGroup()
                        .addGroup(jd_modificarproductoventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_modificaridproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(35, 35, 35)
                        .addComponent(tf_modificarnombreproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15))
                .addGap(38, 38, 38)
                .addGroup(jd_modificarproductoventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_modificartipoproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(38, 38, 38)
                .addComponent(jb_modfinalproducto)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLabel18.setText("IdLaboratorio");

        jLabel19.setText("Nombre Laboratorio");

        jcb_modificarlaboratorio.setModel(new DefaultComboBoxModel());

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_modificarLabLayout = new javax.swing.GroupLayout(jd_modificarLab.getContentPane());
        jd_modificarLab.getContentPane().setLayout(jd_modificarLabLayout);
        jd_modificarLabLayout.setHorizontalGroup(
            jd_modificarLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarLabLayout.createSequentialGroup()
                .addGroup(jd_modificarLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificarLabLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jd_modificarLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_modificarLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtmodifcarnombrelaboratorio)
                            .addComponent(jcb_modificarlaboratorio, 0, 110, Short.MAX_VALUE)))
                    .addGroup(jd_modificarLabLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButton3)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jd_modificarLabLayout.setVerticalGroup(
            jd_modificarLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarLabLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jd_modificarLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jcb_modificarlaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_modificarLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jtxtmodifcarnombrelaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jButton3)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel17.setText("jLabel17");

        jb_eliminarpersona.setText("Persona");
        jb_eliminarpersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarpersonaActionPerformed(evt);
            }
        });

        jb_eliminarlaboratorio.setText("Laboratorio");
        jb_eliminarlaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarlaboratorioActionPerformed(evt);
            }
        });

        jb_eliminarproducto.setText("Producto");
        jb_eliminarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarproductoActionPerformed(evt);
            }
        });

        jb_eliminarfarmacia.setText("Farmacia");
        jb_eliminarfarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarfarmaciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_eliminarLayout = new javax.swing.GroupLayout(jd_eliminar.getContentPane());
        jd_eliminar.getContentPane().setLayout(jd_eliminarLayout);
        jd_eliminarLayout.setHorizontalGroup(
            jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminarLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_eliminarlaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_eliminarfarmacia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_eliminarpersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_eliminarproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jd_eliminarLayout.setVerticalGroup(
            jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminarLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jb_eliminarfarmacia)
                .addGap(27, 27, 27)
                .addComponent(jb_eliminarproducto)
                .addGap(38, 38, 38)
                .addComponent(jb_eliminarlaboratorio)
                .addGap(35, 35, 35)
                .addComponent(jb_eliminarpersona)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jt_eliminarfarmacia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "_id_", "NombreF", "IdF", "Direccion"
            }
        ));
        jScrollPane10.setViewportView(jt_eliminarfarmacia);

        jbt_eliminarfarmacias.setText("Eliminar");
        jbt_eliminarfarmacias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_eliminarfarmaciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_EliminarFarmaciaLayout = new javax.swing.GroupLayout(jd_EliminarFarmacia.getContentPane());
        jd_EliminarFarmacia.getContentPane().setLayout(jd_EliminarFarmaciaLayout);
        jd_EliminarFarmaciaLayout.setHorizontalGroup(
            jd_EliminarFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_EliminarFarmaciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jd_EliminarFarmaciaLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jbt_eliminarfarmacias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_EliminarFarmaciaLayout.setVerticalGroup(
            jd_EliminarFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EliminarFarmaciaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jbt_eliminarfarmacias)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jt_eliminarproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "_id", "IdProducto", "NombreProducto", "Tipo"
            }
        ));
        jScrollPane5.setViewportView(jt_eliminarproductos);

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_EliminarProductoLayout = new javax.swing.GroupLayout(jd_EliminarProducto.getContentPane());
        jd_EliminarProducto.getContentPane().setLayout(jd_EliminarProductoLayout);
        jd_EliminarProductoLayout.setHorizontalGroup(
            jd_EliminarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EliminarProductoLayout.createSequentialGroup()
                .addGroup(jd_EliminarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_EliminarProductoLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_EliminarProductoLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jButton4)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jd_EliminarProductoLayout.setVerticalGroup(
            jd_EliminarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EliminarProductoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jButton4)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jt_eliminarlaboratorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "_id", "IdL", "NombreL"
            }
        ));
        jScrollPane8.setViewportView(jt_eliminarlaboratorios);

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_EliminarLaboratorioLayout = new javax.swing.GroupLayout(jd_EliminarLaboratorio.getContentPane());
        jd_EliminarLaboratorio.getContentPane().setLayout(jd_EliminarLaboratorioLayout);
        jd_EliminarLaboratorioLayout.setHorizontalGroup(
            jd_EliminarLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EliminarLaboratorioLayout.createSequentialGroup()
                .addGroup(jd_EliminarLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_EliminarLaboratorioLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_EliminarLaboratorioLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jButton5)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jd_EliminarLaboratorioLayout.setVerticalGroup(
            jd_EliminarLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EliminarLaboratorioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButton5)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jt_eliminarpersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "_id", "IdP", "NombreP"
            }
        ));
        jScrollPane6.setViewportView(jt_eliminarpersonas);

        jButton6.setText("Eliminar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_EliminarPersonasLayout = new javax.swing.GroupLayout(jd_EliminarPersonas.getContentPane());
        jd_EliminarPersonas.getContentPane().setLayout(jd_EliminarPersonasLayout);
        jd_EliminarPersonasLayout.setHorizontalGroup(
            jd_EliminarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EliminarPersonasLayout.createSequentialGroup()
                .addGroup(jd_EliminarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_EliminarPersonasLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_EliminarPersonasLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jButton6)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jd_EliminarPersonasLayout.setVerticalGroup(
            jd_EliminarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EliminarPersonasLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButton6)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_crear.setText("Crear");
        jb_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearActionPerformed(evt);
            }
        });

        jb_modificar.setText("Modificar");
        jb_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarActionPerformed(evt);
            }
        });

        jb_eliminar.setText("Eliminar");
        jb_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jb_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_crear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jb_crear)
                .addGap(40, 40, 40)
                .addComponent(jb_modificar)
                .addGap(51, 51, 51)
                .addComponent(jb_eliminar)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearActionPerformed
        jd_crear.pack();
        jd_crear.setModal(true);
        jd_crear.setLocationRelativeTo(this);
        jd_crear.setVisible(true);

    }//GEN-LAST:event_jb_crearActionPerformed

    private void jb_crearfarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearfarmaciaActionPerformed
        personaconexion.obtenerProductos(jt_productosxfarmacia);
        personaconexion.obtenerPersonas(jt_personasxfarmacia);
        productos = new ArrayList();
        farmaceuticos = new ArrayList();
        propietarios = new ArrayList();
        jd_crearfarmacia.pack();
        jd_crearfarmacia.setModal(true);
        jd_crearfarmacia.setLocationRelativeTo(this);
        jd_crearfarmacia.setVisible(true);
    }//GEN-LAST:event_jb_crearfarmaciaActionPerformed

    private void jb_crearpersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearpersonaActionPerformed
        jd_crearpersona.pack();
        jd_crearpersona.setModal(true);
        jd_crearpersona.setLocationRelativeTo(this);
        jd_crearpersona.setVisible(true);
    }//GEN-LAST:event_jb_crearpersonaActionPerformed

    private void jb_crearlabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearlabActionPerformed
        personaconexion.obtenerProductos(jt_productosxlaboratorio);
        productos = new ArrayList();
        jd_crearlaboratorio.pack();
        jd_crearlaboratorio.setModal(true);
        jd_crearlaboratorio.setLocationRelativeTo(this);
        jd_crearlaboratorio.setVisible(true);

    }//GEN-LAST:event_jb_crearlabActionPerformed

    private void jtxt_idpersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_idpersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_idpersonaActionPerformed

    private void jb_registrarpersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_registrarpersonaActionPerformed
        persona = new Persona(jtxt_idpersona.getText(), jtxt_nombrepersona.getText());
        personaconexion = new PersonaConexion(persona);
        personaconexion.crearPersona();
    }//GEN-LAST:event_jb_registrarpersonaActionPerformed

    private void jtxt_idfarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_idfarmaciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_idfarmaciaActionPerformed

    private void jb_registrarfarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_registrarfarmaciaActionPerformed
        farmacia = new Farmacia(jtxt_idfarmacia.getText(), jtxt_nombrefarmacia.getText(), jtxt_direccion.getText());
        personaconexion = new PersonaConexion(farmacia);
        farmacia.setProductos(productos);
        farmacia.setFarmaceuticos(farmaceuticos);
        farmacia.setPropietarios(propietarios);
        System.out.println(farmacia.getProductos().get(0).toString());
        personaconexion.crearFarmacia();
    }//GEN-LAST:event_jb_registrarfarmaciaActionPerformed

    private void jtxt_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_direccionActionPerformed

    private void jtxt_idlaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_idlaboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_idlaboratorioActionPerformed

    private void jb_registrarlaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_registrarlaboratorioActionPerformed
        laboratorio = new Laboratorio(jtxt_idlaboratorio.getText(), jtxt_nombrelaboratorio.getText());
        personaconexion = new PersonaConexion(laboratorio);
        laboratorio.setProductos(productos);
        personaconexion.crearLaboratorio();
    }//GEN-LAST:event_jb_registrarlaboratorioActionPerformed

    private void jb_agregarproductoxfarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarproductoxfarmaciaActionPerformed

        producto = new Producto((String) jt_productosxfarmacia.getValueAt(jt_productosxfarmacia.getSelectedRow(), 1), (String) jt_productosxfarmacia.getValueAt(jt_productosxfarmacia.getSelectedRow(), 2), (String) jt_productosxfarmacia.getValueAt(jt_productosxfarmacia.getSelectedRow(), 3));
        productos.add(producto);
        for (int i = 0; i < productos.size(); i++) {
            System.out.println(productos.get(i).toString());
        }
    }//GEN-LAST:event_jb_agregarproductoxfarmaciaActionPerformed

    private void jtxt_idproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_idproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_idproductoActionPerformed

    private void jtxt_tipoproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_tipoproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_tipoproductoActionPerformed

    private void jb_registrarfarmacia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_registrarfarmacia1ActionPerformed
        producto = new Producto(jtxt_idproducto.getText(), jtxt_nombreproducto.getText(), jtxt_tipoproducto.getText());
        personaconexion = new PersonaConexion(producto);
        personaconexion.crearProducto();
    }//GEN-LAST:event_jb_registrarfarmacia1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jd_crearproducto.pack();
        jd_crearproducto.setModal(true);
        jd_crearproducto.setLocationRelativeTo(this);
        jd_crearproducto.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jb_agregarproductoxfarmacia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarproductoxfarmacia1ActionPerformed
        persona = new Persona((String) jt_personasxfarmacia.getValueAt(jt_personasxfarmacia.getSelectedRow(), 1),
                (String) jt_personasxfarmacia.getValueAt(jt_personasxfarmacia.getSelectedRow(), 2));
        farmaceuticos.add(persona);
    }//GEN-LAST:event_jb_agregarproductoxfarmacia1ActionPerformed

    private void jb_agregarproductoxfarmacia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarproductoxfarmacia2ActionPerformed
        persona = new Persona((String) jt_personasxfarmacia.getValueAt(jt_personasxfarmacia.getSelectedRow(), 1),
                (String) jt_personasxfarmacia.getValueAt(jt_personasxfarmacia.getSelectedRow(), 2));
        propietarios.add(persona);
    }//GEN-LAST:event_jb_agregarproductoxfarmacia2ActionPerformed

    private void jcb_idPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_idPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_idPersonaActionPerformed

    private void jb_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarActionPerformed
        jd_Modificar.pack();
        jd_Modificar.setModal(true);
        jd_Modificar.setLocationRelativeTo(this);
        jd_Modificar.setVisible(true);
    }//GEN-LAST:event_jb_modificarActionPerformed

    private void jb_crearpersona1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearpersona1ActionPerformed
        personaconexion.updatecb_personas(jcb_idPersona);
        jd_ModificarPersonas.pack();
        jd_ModificarPersonas.setModal(true);
        jd_ModificarPersonas.setLocationRelativeTo(this);
        jd_ModificarPersonas.setVisible(true);

    }//GEN-LAST:event_jb_crearpersona1ActionPerformed

    private void jb_crearlab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearlab1ActionPerformed
        personaconexion.updatecb_laboratorios(jcb_modificarlaboratorio);
        jd_modificarLab.pack();
        jd_modificarLab.setModal(true);
        jd_modificarLab.setLocationRelativeTo(this);
        jd_modificarLab.setVisible(true);
    }//GEN-LAST:event_jb_crearlab1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        personaconexion.obtenerProductos(jt_productos);
        jd_modificarproducto.pack();
        jd_modificarproducto.setModal(true);
        jd_modificarproducto.setLocationRelativeTo(this);
        jd_modificarproducto.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jb_crearfarmacia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearfarmacia1ActionPerformed
        personaconexion.updatecb_farmacias(jcb_idfarmacia);
        jd_ModificarFarmacias.pack();
        jd_ModificarFarmacias.setModal(true);
        jd_ModificarFarmacias.setLocationRelativeTo(this);
        jd_ModificarFarmacias.setVisible(true);
    }//GEN-LAST:event_jb_crearfarmacia1ActionPerformed

    private void jb_modificarpersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarpersonaActionPerformed
        Document d = new Document();
        d = personaconexion.obtenerPersona(new Persona(jcb_idPersona.getSelectedItem().toString(), " "));
        Persona nuevo = new Persona(jcb_idPersona.getSelectedItem().toString(), jtxt_modificarnombrePersona.getText());
        Document d2 = nuevo.toDocument();
        personaconexion.reemplazarPersona(d, d2);
    }//GEN-LAST:event_jb_modificarpersonaActionPerformed

    private void jtxt_modificarnombrefarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_modificarnombrefarmaciaActionPerformed
        Document d = new Document();
        d = personaconexion.obtenerFarmacia(new Farmacia(jcb_idfarmacia.getSelectedItem().toString(), jtxt_modificarnombrePersona.getText(), jtxt_modificardireccionfarmacia.getText()));
        Farmacia nuevo = new Farmacia(jcb_idfarmacia.getSelectedItem().toString(), jtxt_modificarnombrePersona.getText(), jtxt_modificardireccionfarmacia.getText());
        Document d2 = nuevo.toDocument();
        personaconexion.reemplazarPersona(d, d2);
    }//GEN-LAST:event_jtxt_modificarnombrefarmaciaActionPerformed

    private void jb_modificarfarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarfarmaciaActionPerformed
        /*Document d = new Document();
        d = personaconexion.obtenerFarmacia(new Farmacia(jcb_idfarmacia.getSelectedItem().toString(), " "," "));
        Farmacia nuevo = new Farmacia (jcb_idfarmacia.getSelectedItem().toString(), jtxt_modificarnombrefarmacia.getText(),jtxt_modificardireccionfarmacia.getText());
        Document d2 = nuevo.toDocument();    
        personaconexion.reemplazarFarmacia(d, d2);
         */
        BasicDBObject newDocument = new BasicDBObject().append("$set",
                new BasicDBObject().append("NombreF", "" + jtxt_modificarnombrefarmacia.getText() + ""));
        database.getCollection("Farmacia").updateOne(new BasicDBObject().append("IdF", jcb_idfarmacia.getSelectedItem().toString()), newDocument);
        newDocument = new BasicDBObject().append("$set",
                new BasicDBObject().append("Direccion", "" + jtxt_modificardireccionfarmacia.getText() + ""));
        database.getCollection("Farmacia").updateOne(new BasicDBObject().append("IdF", jcb_idfarmacia.getSelectedItem().toString()), newDocument);
        /*BasicDBObject newDocument = new BasicDBObject().append("$set",
                new BasicDBObject().append("ID Laboratorio", "" + id + ""));
        database.getCollection("Laboratorio").updateOne(new BasicDBObject().append("ID Laboratorio", jt_laboratorios1.getValueAt(jt_laboratorios1.getSelectedRow(), 1).toString()), newDocument);
        newDocument = new BasicDBObject().append("$set",
                new BasicDBObject().append("Nombre", "" + nombrefar + ""));
        database.getCollection("L");
         */
    }//GEN-LAST:event_jb_modificarfarmaciaActionPerformed

    private void jb_modificarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarproductoActionPerformed
        consulta = new Document();
        if (jt_productos.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un elemento de la tabla para poder modificar");
        } else {
            DefaultTableModel modelo = (DefaultTableModel) jt_productos.getModel();
            String id = (String) modelo.getValueAt(jt_productos.getSelectedRow(), 1);
            Producto pr = new Producto(id);
            consulta = personaconexion.obtenerProducto(pr);
            ArrayList<String> empresita = new ArrayList();
            String principal = "";
            String[] p;
            principal = consulta.toString();
            p = principal.split(",");
            for (int i = 0; i < p.length; i++) {
                String f[] = p[i].split("=");
                empresita.add(f[1]);
            }
            String nom = "";
            for (int i = 0; i < empresita.get(2).length(); i++) {
                if (empresita.get(2).charAt(i) != '}') {
                    nom += empresita.get(2).charAt(i);
                }
            }
            tf_modificarnombreproducto.setText(nom);
            tf_modificaridproducto.setText(empresita.get(1));

            jd_modificarproductoventana.setModal(true);
            jd_modificarproductoventana.pack();
            jd_modificarproductoventana.setLocationRelativeTo(this);
            jd_modificarproductoventana.setVisible(true);
        }

    }//GEN-LAST:event_jb_modificarproductoActionPerformed

    private void jb_modfinalproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modfinalproductoActionPerformed
        String id, nombre, tipo;
        id = tf_modificaridproducto.getText();
        tf_modificaridproducto.setText("");
        nombre = tf_modificarnombreproducto.getText();
        tf_modificarnombreproducto.setText("");
        tipo = tf_modificartipoproducto.getText();
        tf_modificartipoproducto.setText("");
        Producto pr = new Producto(id, nombre, tipo);
        PersonaConexion pc = new PersonaConexion();
        pc.reemplazarProducto(consulta, pr.toDocument());
        pc.obtenerProductos(jt_productos);
        JOptionPane.showMessageDialog(this, "Se modifico exitosamente");
        jd_modificarproductoventana.dispose();
    }//GEN-LAST:event_jb_modfinalproductoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Document d = new Document();
        d = personaconexion.obtenerLaboratorio(new Laboratorio(jcb_modificarlaboratorio.getSelectedItem().toString(), " "));
        Laboratorio nuevo = new Laboratorio(jcb_modificarlaboratorio.getSelectedItem().toString(), jtxtmodifcarnombrelaboratorio.getText());
        Document d2 = nuevo.toDocument();
        personaconexion.reemplazarLaboratorio(d, d2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jb_agregarproductoxfarmacia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarproductoxfarmacia3ActionPerformed
        producto = new Producto((String) jt_productosxlaboratorio.getValueAt(jt_productosxlaboratorio.getSelectedRow(), 1), (String) jt_productosxlaboratorio.getValueAt(jt_productosxlaboratorio.getSelectedRow(), 2), (String) jt_productosxlaboratorio.getValueAt(jt_productosxlaboratorio.getSelectedRow(), 3));
        productos.add(producto);
    }//GEN-LAST:event_jb_agregarproductoxfarmacia3ActionPerformed

    private void jb_eliminarpersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarpersonaActionPerformed
        personaconexion.obtenerPersonas(jt_eliminarpersonas);
        jd_EliminarPersonas.pack();
        jd_EliminarPersonas.setModal(true);
        jd_EliminarPersonas.setLocationRelativeTo(this);
        jd_EliminarPersonas.setVisible(true);
    }//GEN-LAST:event_jb_eliminarpersonaActionPerformed

    private void jb_eliminarlaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarlaboratorioActionPerformed
        personaconexion.obtenerLaboratorios(jt_eliminarlaboratorios);
        jd_EliminarLaboratorio.pack();
        jd_EliminarLaboratorio.setModal(true);
        jd_EliminarLaboratorio.setLocationRelativeTo(this);
        jd_EliminarLaboratorio.setVisible(true);
    }//GEN-LAST:event_jb_eliminarlaboratorioActionPerformed

    private void jb_eliminarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarproductoActionPerformed
        personaconexion.obtenerProductos(jt_eliminarproductos);
        jd_EliminarProducto.pack();
        jd_EliminarProducto.setModal(true);
        jd_EliminarProducto.setLocationRelativeTo(this);
        jd_EliminarProducto.setVisible(true);
    }//GEN-LAST:event_jb_eliminarproductoActionPerformed

    private void jb_eliminarfarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarfarmaciaActionPerformed
        personaconexion.obtenerFarmacia(jt_eliminarfarmacia);
        jd_EliminarFarmacia.pack();
        jd_EliminarFarmacia.setModal(true);
        jd_EliminarFarmacia.setLocationRelativeTo(this);
        jd_EliminarFarmacia.setVisible(true);

    }//GEN-LAST:event_jb_eliminarfarmaciaActionPerformed

    private void jb_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarActionPerformed
        jd_eliminar.pack();
        jd_eliminar.setModal(true);
        jd_eliminar.setLocationRelativeTo(this);
        jd_eliminar.setVisible(true);

    }//GEN-LAST:event_jb_eliminarActionPerformed

    private void jbt_eliminarfarmaciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_eliminarfarmaciasActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jt_eliminarfarmacia.getModel();
        String farmacia = (String) modelo.getValueAt(jt_eliminarfarmacia.getSelectedRow(), 2);
        System.out.println("ID " + farmacia);
        Farmacia pl = new Farmacia(farmacia);
        consulta = new Document();
        consulta = personaconexion.obtenerFarmacia(pl);
        personaconexion.eliminarFarmacia(consulta);
        JOptionPane.showMessageDialog(this, "Registro eliminado exitosamente");
        personaconexion.obtenerFarmacia(jt_eliminarfarmacia);
    }//GEN-LAST:event_jbt_eliminarfarmaciasActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jt_eliminarproductos.getModel();
        String producto = (String) modelo.getValueAt(jt_eliminarproductos.getSelectedRow(), 1);
        System.out.println("ID " + producto);
        Producto pl = new Producto(producto);
        consulta = new Document();
        consulta = personaconexion.obtenerProducto(pl);
        personaconexion.eliminarProducto(consulta);
        JOptionPane.showMessageDialog(this, "Registro eliminado exitosamente");
        personaconexion.obtenerProductos(jt_eliminarproductos);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jt_eliminarlaboratorios.getModel();
        String laboratorio = (String) modelo.getValueAt(jt_eliminarlaboratorios.getSelectedRow(), 1);
        System.out.println("ID " + laboratorio);
        Laboratorio pl = new Laboratorio(laboratorio);
        consulta = new Document();
        consulta = personaconexion.obtenerLaboratorio(pl);
        personaconexion.eliminarLaboratorio(consulta);
        JOptionPane.showMessageDialog(this, "Registro eliminado exitosamente");
        personaconexion.obtenerLaboratorios(jt_eliminarlaboratorios);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jt_eliminarpersonas.getModel();
        String personas = (String) modelo.getValueAt(jt_eliminarpersonas.getSelectedRow(), 1);
        System.out.println("ID " + personas);
        Persona pl = new Persona(personas);
        consulta = new Document();
        consulta = personaconexion.obtenerPersona(pl);
        personaconexion.eliminarPersona(consulta);
        JOptionPane.showMessageDialog(this, "Registro eliminado exitosamente");
        personaconexion.obtenerPersonas(jt_eliminarpersonas);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProyectoBD2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProyectoBD2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProyectoBD2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectoBD2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProyectoBD2().setVisible(true);
            }
        });
        MongoClient mongoClient = MongoClients.create(
                "mongodb+srv://JoseDanielRC:Daniel08@cluster0.nvrwy.mongodb.net/test?retryWrites=true&w=majority");
        MongoDatabase database = mongoClient.getDatabase("test");
        //database.createCollection(" Personas");
        /*Persona persona = new Persona("0402", "Jasser Shelby");
        personaconexion = new PersonaConexion(persona);
        personaconexion.crearPersona();*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JButton jb_agregarproductoxfarmacia;
    private javax.swing.JButton jb_agregarproductoxfarmacia1;
    private javax.swing.JButton jb_agregarproductoxfarmacia2;
    private javax.swing.JButton jb_agregarproductoxfarmacia3;
    private javax.swing.JButton jb_crear;
    private javax.swing.JButton jb_crearfarmacia;
    private javax.swing.JButton jb_crearfarmacia1;
    private javax.swing.JButton jb_crearlab;
    private javax.swing.JButton jb_crearlab1;
    private javax.swing.JButton jb_crearpersona;
    private javax.swing.JButton jb_crearpersona1;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JButton jb_eliminarfarmacia;
    private javax.swing.JButton jb_eliminarlaboratorio;
    private javax.swing.JButton jb_eliminarpersona;
    private javax.swing.JButton jb_eliminarproducto;
    private javax.swing.JButton jb_modfinalproducto;
    private javax.swing.JButton jb_modificar;
    private javax.swing.JButton jb_modificarfarmacia;
    private javax.swing.JButton jb_modificarpersona;
    private javax.swing.JButton jb_modificarproducto;
    private javax.swing.JButton jb_registrarfarmacia;
    private javax.swing.JButton jb_registrarfarmacia1;
    private javax.swing.JButton jb_registrarlaboratorio;
    private javax.swing.JButton jb_registrarpersona;
    private javax.swing.JButton jbt_eliminarfarmacias;
    private javax.swing.JComboBox<String> jcb_idPersona;
    private javax.swing.JComboBox<String> jcb_idfarmacia;
    private javax.swing.JComboBox<String> jcb_modificarlaboratorio;
    private javax.swing.JDialog jd_EliminarFarmacia;
    private javax.swing.JDialog jd_EliminarLaboratorio;
    private javax.swing.JDialog jd_EliminarPersonas;
    private javax.swing.JDialog jd_EliminarProducto;
    private javax.swing.JDialog jd_Modificar;
    private javax.swing.JDialog jd_ModificarFarmacias;
    private javax.swing.JDialog jd_ModificarPersonas;
    private javax.swing.JDialog jd_crear;
    private javax.swing.JDialog jd_crearfarmacia;
    private javax.swing.JDialog jd_crearlaboratorio;
    private javax.swing.JDialog jd_crearpersona;
    private javax.swing.JDialog jd_crearproducto;
    private javax.swing.JDialog jd_eliminar;
    private javax.swing.JDialog jd_modificarLab;
    private javax.swing.JDialog jd_modificarproducto;
    private javax.swing.JDialog jd_modificarproductoventana;
    private javax.swing.JTable jt_eliminarfarmacia;
    private javax.swing.JTable jt_eliminarlaboratorios;
    private javax.swing.JTable jt_eliminarpersonas;
    private javax.swing.JTable jt_eliminarproductos;
    private javax.swing.JTable jt_personasxfarmacia;
    private javax.swing.JTable jt_productos;
    private javax.swing.JTable jt_productosxfarmacia;
    private javax.swing.JTable jt_productosxlaboratorio;
    private javax.swing.JTextField jtxt_direccion;
    private javax.swing.JTextField jtxt_idfarmacia;
    private javax.swing.JTextField jtxt_idlaboratorio;
    private javax.swing.JTextField jtxt_idpersona;
    private javax.swing.JTextField jtxt_idproducto;
    private javax.swing.JTextField jtxt_modificardireccionfarmacia;
    private javax.swing.JTextField jtxt_modificarnombrePersona;
    private javax.swing.JTextField jtxt_modificarnombrefarmacia;
    private javax.swing.JTextField jtxt_nombrefarmacia;
    private javax.swing.JTextField jtxt_nombrelaboratorio;
    private javax.swing.JTextField jtxt_nombrepersona;
    private javax.swing.JTextField jtxt_nombreproducto;
    private javax.swing.JTextField jtxt_tipoproducto;
    private javax.swing.JTextField jtxtmodifcarnombrelaboratorio;
    private javax.swing.JTextField tf_modificaridproducto;
    private javax.swing.JTextField tf_modificarnombreproducto;
    private javax.swing.JTextField tf_modificartipoproducto;
    // End of variables declaration//GEN-END:variables
}
